import pytest
import os
import numpy as np
import torch
import yaml
import shutil

from mentat_lss.training_loops import train_on_single_device, train_on_multiple_devices
from mentat_lss.utils import get_parameter_ranges, load_config_file, make_latin_hypercube, make_hypersphere, is_in_hypersphere, organize_training_set, calc_chi2_statistics
from mentat_lss.emulator import ps_emulator

# This file contains e2e tests for the full mentat-lss package

def is_fiducial_cosmology_in_hyperspere(cosmo_dict, param_ranges):
    cosmo_fid = []
    for param in cosmo_dict["cosmo_params"].keys():
        if "prior" in cosmo_dict["cosmo_params"][param]:
            cosmo_fid.append(cosmo_dict["cosmo_params"][param]["value"])
    for param in cosmo_dict["nuisance_params"].keys():
        if "prior" in cosmo_dict["nuisance_params"][param]:
            cosmo_fid.append(cosmo_dict["nuisance_params"][param]["value"])

    return is_in_hypersphere(param_ranges, np.array(cosmo_fid))

def prepare_header_info(param_names, fiducial_cosmology, n_samples):
    header_info = {}
    header_info["total_samples"] = n_samples
    cosmo_params = []
    bias_params = []
    for key in fiducial_cosmology["cosmo_params"].keys():
        if key in param_names:
            cosmo_params.append(key)
    for key in fiducial_cosmology["nuisance_params"].keys():
        if key in param_names:
            bias_params.append(key)

    header_info["cosmo_params"] = cosmo_params
    header_info["nuisance_params"] = bias_params
    return header_info

def generate_small_training_set(cosmo_dict, net_dict):
    """Generates a small training set for testing purposes. 
    This method is essentially a simpler version of scripts/make_training_set.py"""

    save_dir = net_dict["training_dir"]
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    param_names, param_ranges = get_parameter_ranges(cosmo_dict)
    N = 100

    if   net_dict["sampling_type"] == "hypercube":   
        all_samples = make_latin_hypercube(param_ranges, N)
    elif net_dict["sampling_type"] == "hypersphere": 
        all_samples = make_hypersphere(param_ranges, len(param_ranges), N)
        is_valid_cosmo, r = is_fiducial_cosmology_in_hyperspere(cosmo_dict, param_ranges)
        assert is_valid_cosmo, "Fiducial cosmology is not in the hypersphere defined by the parameter ranges. Please adjust the parameter ranges or fiducial cosmology in the test config file."

    ps_properties = np.load(os.path.join(save_dir,"ps_properties.npz"))
    num_kbins = len(ps_properties["k"])
    num_ells = len(ps_properties["ells"])
    num_zbins = len(ps_properties["z_eff"])
    num_tracers = ps_properties["ndens"].shape[0]
    num_spectra = num_tracers + (num_tracers*(num_tracers-1))//2

    # populate "power spectra" with random values for testing purposes
    ps_shape = (N, num_spectra, num_zbins, num_kbins, num_ells)
    galaxy_ps = np.random.rand(*ps_shape)
    np.savez(os.path.join(save_dir,"pk-raw_0_.npz"), params=all_samples, galaxy_ps=galaxy_ps)

    ps_fid = np.random.rand(1, num_spectra, num_zbins, num_kbins, num_ells)
    np.save(os.path.join(save_dir,"ps_fid.npy"), ps_fid)

    dataset_info = prepare_header_info(param_names, cosmo_dict, N)
    with open(os.path.join(save_dir,'info.yaml'), 'w') as outfile:
            yaml.dump(dataset_info, outfile, sort_keys=False, default_flow_style=False)

    organize_training_set(save_dir, 0.8, 0.1, 0.1, len(param_names), num_zbins, num_spectra, num_ells, num_kbins, True)

def train_small_network(net_config_file):
    """Trains a network on the small training set generated by generate_small_training_set()"""
    test_emulator = ps_emulator(net_config_file, "train", device="cpu")
    train_on_single_device(test_emulator)
    # TODO: Add branch for train_on_multiple_devices

    return test_emulator


def clean_small_training_set(net_dict):
    save_dir = net_dict["training_dir"]
    if os.path.exists(save_dir):
        if os.path.exists(os.path.join(save_dir,"ps_fid.npy")):
            os.remove(os.path.join(save_dir,"ps_fid.npy"))
        if os.path.exists(os.path.join(save_dir,"info.yaml")):
            os.remove(os.path.join(save_dir,"info.yaml"))
        if os.path.exists(os.path.join(save_dir,"pk-raw_0_.npz")):
            os.remove(os.path.join(save_dir,"pk-raw_0_.npz"))
        elif os.path.exists(os.path.join(save_dir,"pk-training.npz")):
            os.remove(os.path.join(save_dir,"pk-training.npz"))
            os.remove(os.path.join(save_dir,"pk-validation.npz"))
            os.remove(os.path.join(save_dir,"pk-testing.npz"))


@pytest.mark.parametrize("net_type", [
    ("stacked_transformer"),
    ("combined_tracer_transformer"), 
])
def test_ps_emulator_workflow(net_type):
    """Tests the full workflow of the ps_emulator, from generating a training set to training the network and saving the results. 
    This test is meant to be run with a small training set generated by generate_small_training_set()"""
    
    current_dir = os.path.dirname(os.path.realpath(__file__))
    net_config_file = os.path.join(current_dir, "test_configs", f"network_pars_{net_type}.yaml")
    net_config = load_config_file(net_config_file)
    cosmo_dict = load_config_file(os.path.join(current_dir, "test_configs", "cosmo_pars_2t_2z.yaml"))

    clean_small_training_set(net_config) # in case previous test runs left files behind
    generate_small_training_set(cosmo_dict, net_config)

    test_emulator = train_small_network(net_config_file)
    test_loader = test_emulator.load_data("testing", 1.0, True, net_config["training_dir"])

    chi2_sub, chi2_combined = calc_chi2_statistics(test_emulator, test_loader)
    assert torch.all(torch.isnan(chi2_sub)) == False, "Delta chi2 statistics contain NaN values. There may be an issue with the emulator predictions or the test dataset."
    assert torch.all(torch.isnan(chi2_combined)) == False, "Delta chi2 statistics contain NaN values. There may be an issue with the emulator predictions or the test dataset."

    clean_small_training_set(net_config)