# File containing fiducial and prior values
# NOTE: This file will be very long if using all redshift and sample bins

# Fiducial model for the EFT power spectrum
# Based on planck 2018 cosmology

cosmo_param_names:
  - h
  - ombh2
  - omch2
  - As
  - ns 
  - fnl
bias_param_names:
  - galaxy_bias_10     # b1
  - galaxy_bias_20     # b2
  - galaxy_bias_G2     # bG2
  - galaxy_bias_Gamma3 # bGamma3
  - galaxy_bias_01     # bphi
  - galaxy_bias_11     # bphid
counterterm_param_names:
  - counterterm_0
  - counterterm_2
  - counterterm_4
  - counterterm_fog
stochastic_param_names:
  - P_shot
  - a0
  - a2

cosmo_params:
  h: 
    value: 0.6736
  ombh2: 
    value: 0.02237
  omch2:
    value: 0.1201
    prior:
      min: 0.05
      max: 0.2
  As:
    value: 2.1e-9
    prior:
      min: 1.7e-9
      max: 2.5e-9
  ns:
    value: 0.96589
    prior:
      min: 0.9
      max: 1.1
  fnl:
    value: 0
    prior:
      min: -50
      max: 50

# bias parameter names take the form <parameter_sample_redshift>
# if just <parameter> is given, will assume that value is constant for all redshift and
# sample bins (unrealistic)
# Default values for a specific value of b1 can be calcuated from https://github.com/SPHEREx/Cosmo_Inference/blob/develop/src/lss_theory/lss_theory/data_vector/cosmo_formulas.py 
nuisance_params:
  galaxy_bias_10_0_0:
    value: 1.5
    prior:
      min: 0.5
      max: 3
  galaxy_bias_10_1_0:
    value: 1.3
    prior:
      min: 0.5
      max: 3
  galaxy_bias_10_0_1:
    value: 1.8
    prior:
      min: 0.5
      max: 3
  galaxy_bias_10_1_1:
    value: 1.4
    prior:
      min: 0.5
      max: 3
  galaxy_bias_20_0_0:
    value: -1.37
    prior:
      min: -2
      max: -0.25
  galaxy_bias_20_1_0:
    value: -1.572
    prior:
      min: -2
      max: -0.25
  galaxy_bias_20_0_1:
    value: -0.78
    prior:
      min: -2
      max: -0.25
  galaxy_bias_20_1_1:
    value: -1.49
    prior:
      min: -2
      max: -0.25
  galaxy_bias_G2_0_0:
    value: -0.286
    prior:
      min: -0.75
      max: 0.1
  galaxy_bias_G2_1_0:
    value: -0.17
    prior:
      min: -0.75
      max: 0.1
  galaxy_bias_G2_0_1:
    value: -0.457
    prior:
      min: -0.75
      max: 0.1
  galaxy_bias_G2_1_1:
    value: -0.228
    prior:
      min: -0.75
      max: 0.1
  galaxy_bias_Gamma3:
    value: 0
  galaxy_bias_01_0_0:
    value: 2.6976
  galaxy_bias_01_1_0:
    value: 2.6976
  galaxy_bias_01_0_1:
    value: 2.6976
  galaxy_bias_01_1_1:
    value: 2.6976
  galaxy_bias_11:
    value: 0
  counterterm_0_0_0:
    value: 0
    prior:
      min: -75
      max: 75
  counterterm_0_1_0:
    value: 0
    prior:
      min: -75
      max: 75
  counterterm_0_0_1:
    value: 0
    prior:
      min: -75
      max: 75
  counterterm_0_1_1:
    value: 0
    prior:
      min: -75
      max: 75
  counterterm_2_0_0:
    value: 0
    prior:
      min: -75
      max: 75
  counterterm_2_1_0:
    value: 0
    prior:
      min: -75
      max: 75
  counterterm_2_0_1:
    value: 0
    prior:
      min: -75
      max: 75
  counterterm_2_1_1:
    value: 0
    prior:
      min: -75
      max: 75
  counterterm_4:
    value: 0
  counterterm_fog_0_0:
    value: 0
    prior:
      min: -40
      max: 40
  counterterm_fog_1_0:
    value: 0
    prior:
      min: -40
      max: 40
  counterterm_fog_0_1:
    value: 0
    prior:
      min: -40
      max: 40
  counterterm_fog_1_1:
    value: 0
    prior:
      min: -40
      max: 40
  # Yosuke's code automatically calulates P_shot = 1/n, so should be set to 1 for now
  P_shot:
    value: 0
  a0:
    value: 0
  a2:
    value: 0