# File containing fiducial and prior values
# NOTE: This file will be very long if using all redshift and sample bins

# Fiducial model for the EFT power spectrum
# Based on planck 2018 cosmology and
# The DESI DR1 full-shape analysis priors

cosmo_param_names:
  - h
  - ombh2
  - omch2
  - As
  - ns 
  - fnl
bias_param_names:
  - galaxy_bias_10     # b1
  - galaxy_bias_20     # b2
  - galaxy_bias_G2     # bG2
  - galaxy_bias_Gamma3 # bGamma3
  - galaxy_bias_01     # bphi
  - galaxy_bias_11     # bphid
counterterm_param_names:
  - counterterm_0
  - counterterm_2
  - counterterm_4
  - counterterm_fog
stochastic_param_names:
  - P_shot
  - stochasticity_a0
  - stochasticity_a2

cosmo_params:
  h: 
    value: 0.6736
    prior:
      min: 0.45
      max: 0.95
  ombh2: 
    value: 0.02218
    prior:
      min: 0.02053
      max: 0.02383
  omch2:
    value: 0.1201
    prior:
      min: 0.075
      max: 0.2
  As:
    value: 2.1e-9
    prior:
      min: 1.0e-9
      max: 3.0e-9
  ns:
    value: 0.96589
    prior:
      min: 0.9
      max: 1.05
  fnl:
    value: 0

# bias parameter names take the form <parameter_sample_redshift>
# if just <parameter> is given, will assume that value is constant for all redshift and
# sample bins (unrealistic)
# Default values for a specific value of b1 can be calcuated from https://github.com/SPHEREx/Cosmo_Inference/blob/develop/src/lss_theory/lss_theory/data_vector/cosmo_formulas.py 
nuisance_params:
  galaxy_bias_10_0_0:
    value: 1.5
    prior:
      min: 1.0
      max: 4.0
  galaxy_bias_10_1_0:
    value: 1.3
    prior:
      min: 1.0
      max: 4.0
  galaxy_bias_10_0_1:
    value: 1.8
    prior:
      min: 1.0
      max: 4.0
  galaxy_bias_10_1_1:
    value: 1.4
    prior:
      min: 1.0
      max: 4.0
  galaxy_bias_20_0_0:
    value: -1.37
    prior:
      min: -2
      max: 1
  galaxy_bias_20_1_0:
    value: -1.572
    prior:
      min: -2
      max: 1
  galaxy_bias_20_0_1:
    value: -0.78
    prior:
      min: -2
      max: 1
  galaxy_bias_20_1_1:
    value: -1.49
    prior:
      min: -2
      max: 1
  galaxy_bias_G2_0_0:
    value: -0.286
    prior:
      min: -1.5
      max: 1.5
  galaxy_bias_G2_1_0:
    value: -0.17
    prior:
      min: -1.5
      max: 1.5
  galaxy_bias_G2_0_1:
    value: -0.457
    prior:
      min: -1.5
      max: 1.5
  galaxy_bias_G2_1_1:
    value: -0.228
    prior:
      min: -1.5
      max: 1.5
  galaxy_bias_Gamma3:
    value: 0
  galaxy_bias_01_0_0:
    value: 0
  galaxy_bias_01_1_0:
    value: 0
  galaxy_bias_01_0_1:
    value: 0
  galaxy_bias_01_1_1:
    value: 0
  galaxy_bias_11:
    value: 0
  counterterm_0_0_0:
    value: 0
    prior:
      min: -90
      max: 90
  counterterm_0_1_0:
    value: 0
    prior:
      min: -90
      max: 90
  counterterm_0_0_1:
    value: 0
    prior:
      min: -90
      max: 90
  counterterm_0_1_1:
    value: 0
    prior:
      min: -90
      max: 90
  counterterm_2_0_0:
    value: 0
    prior:
      min: -90
      max: 90
  counterterm_2_1_0:
    value: 0
    prior:
      min: -90
      max: 90
  counterterm_2_0_1:
    value: 0
    prior:
      min: -90
      max: 90
  counterterm_2_1_1:
    value: 0
    prior:
      min: -90
      max: 90
  counterterm_4:
    value: 0
  counterterm_fog_0_0:
    value: 0
    prior:
      min: -500
      max: 1500
  counterterm_fog_1_0:
    value: 0
    prior:
      min: -500
      max: 1500
  counterterm_fog_0_1:
    value: 0
    prior:
      min: -500
      max: 1500
  counterterm_fog_1_1:
    value: 0
    prior:
      min: -500
      max: 1500
  # Should all be set to 0 when making a training set so we aren't emulating trivial parameters
  P_shot:
    value: 0
  stochasticity_a0:
    value: 0
  stochasticity_a2:
    value: 0