# File containing fiducial and prior values
# NOTE: This file will be very long if using all redshift and sample bins

# Fiducial model for the EFT power spectrum
# Based on planck 2018 cosmology

varied_cosmo_params: 3
varied_bias_params: 7

cosmo_param_names:
  - h
  - omega_b
  - omega_c
  - As
  - ns 
  - fnl
bias_param_names:
  - b1
  - b2
  - bG2
  - bGamma3
  - bphi
  - bphid
  - c0
  - c2
  - c4
  - cfog
  - P_shot
  - a0
  - a2

cosmo_params:
  h: 
    value: 0.6736
  omega_b: 
    value: 0.02237
  omega_c:
    value: 0.1201
  As:
    value: 2.1e-9
    prior:
      min: 1.7e-9
      max: 2.5e-9
  ns:
    value: 0.96589
    prior:
      min: 0.9
      max: 1.1
  fnl:
    value: 0
    prior:
      min: -50
      max: 50

# bias parameter names take the form <parameter_sample_redshift>
# if just <parameter> is given, will assume that value is constant for all redshift and
# sample bins (unrealistic)
# Default values for a specific value of b1 can be calcuated from https://github.com/SPHEREx/Cosmo_Inference/blob/develop/src/lss_theory/lss_theory/data_vector/cosmo_formulas.py 
bias_params:
  b1_0_0:
    value: 1.5
    prior:
      min: 0.5
      max: 3
  b1_1_0:
    value: 1.3
    prior:
      min: 0.5
      max: 3
  b1_0_1:
    value: 1.8
    prior:
      min: 0.5
      max: 3
  b1_1_1:
    value: 1.4
    prior:
      min: 0.5
      max: 3
  b2_0_0:
    value: -1.37
    prior:
      min: -2
      max: -0.25
  b2_1_0:
    value: -1.572
    prior:
      min: -2
      max: -0.25
  b2_0_1:
    value: -0.78
    prior:
      min: -2
      max: -0.25
  b2_1_1:
    value: -1.49
    prior:
      min: -2
      max: -0.25
  bG2_0_0:
    value: -0.286
    prior:
      min: -0.75
      max: 0.1
  bG2_1_0:
    value: -0.17
    prior:
      min: -0.75
      max: 0.1
  bG2_0_1:
    value: -0.457
    prior:
      min: -0.75
      max: 0.1
  bG2_1_1:
    value: -0.228
    prior:
      min: -0.75
      max: 0.1
  bGamma3:
    value: 0
  bphi_0_0:
    value: 2.6976
  bphi_1_0:
    value: 2.6976
  bphi_0_1:
    value: 2.6976
  bphi_1_1:
    value: 2.6976
  bphid:
    value: 0
  c0_0_0:
    value: 0
    prior:
      min: -75
      max: 75
  c0_1_0:
    value: 0
    prior:
      min: -75
      max: 75
  c0_0_1:
    value: 0
    prior:
      min: -75
      max: 75
  c0_1_1:
    value: 0
    prior:
      min: -75
      max: 75
  c2_0_0:
    value: 0
    prior:
      min: -75
      max: 75
  c2_1_0:
    value: 0
    prior:
      min: -75
      max: 75
  c2_0_1:
    value: 0
    prior:
      min: -75
      max: 75
  c2_1_1:
    value: 0
    prior:
      min: -75
      max: 75
  c4:
    value: 0
  cfog_0_0:
    value: 0
    prior:
      min: -40
      max: 40
  cfog_1_0:
    value: 0
    prior:
      min: -40
      max: 40
  cfog_0_1:
    value: 0
    prior:
      min: -40
      max: 40
  cfog_1_1:
    value: 0
    prior:
      min: -40
      max: 40
  # Yosuke's code automatically calulates P_shot = 1/n, so should be set to 1 for now
  P_shot:
    value: 0
  a0:
    value: 0
  a2:
    value: 0