# File containing fiducial and prior values
# NOTE: This file will be very long if using all redshift and sample bins

# Fiducial model for the EFT power spectrum
# Based on planck 2018 cosmology

varied_cosmo_params: 4
varied_bias_params: 1

cosmo_param_names:
  - h
  - omega_b
  - omega_c
  - As
  - ns 
  - fnl
bias_param_names:
  - b1
  - b2
  - bG2
  - bGamma3
  - bphi
  - bphid
  - c0
  - c2
  - c4
  - cfog
  - P_shot
  - a0
  - a2

cosmo_params:
  h: 
    value: 0.6736
    prior:
      min: 0.45
      max: 1.0
  omega_b: 
    value: 0.02237
  omega_c:
    value: 0.1200
    prior:
      min: 0.06
      max: 0.2
  As:
    value: 2.1e-9
    prior:
      min: 1.2e-9
      max: 2.7e-9
  ns:
    value: 0.9649
  fnl:
    value: 0
    prior:
      min: -50
      max: 50

# bias parameter names take the form <parameter_sample_redshift>
# if just <parameter> is given, will assume that value is constant for all redshift and
# sample bins (unrealistic)
bias_params:
  b1_0_0:
    value: 1.3
    prior:
      min: 1
      max: 4
  b1_0_1:
    value: 1.4
    prior:
      min: 1
      max: 3.5
  b1_1_0:
    value: 1.3
    prior:
      min: 1
      max: 4
  b1_1_1:
    value: 1.5
    prior:
      min: 1
      max: 4
  b2:
    value: -1.
  bG2:
    value: 0.1
  bGamma3:
    value: -0.1
  bphi:
    value: 5
  bphid:
    value: 10
  c0:
    value: 5
  c2:
    value: 10
  c4:
    value: -5
  cfog:
    value: 5
  P_shot:
    value: 10
  a0:
    value: 0
  a2:
    value: 0
