# File containing fiducial and prior values
# NOTE: This file will be very long if using all redshift and sample bins

# Fiducial model for the EFT power spectrum
# Based on planck 2018 cosmology

varied_cosmo_params: 4
varied_bias_params: 1

cosmo_param_names:
  - h
  - omega_b
  - omega_c
  - As
  - ns 
  - fnl
bias_param_names:
  - b1
  - b2
  - bG2
  - bGamma3
  - bphi
  - bphid
  - c0
  - c2
  - c4
  - cfog
  - P_shot
  - a0
  - a2

cosmo_params:
  h: 
    value: 0.6736
  omega_b: 
    value: 0.02237
  omega_c:
    value: 0.1201
  As:
    value: 2.1e-9
  ns:
    value: 0.96589
  fnl:
    value: 0
    prior:
      min: -50
      max: 50

# bias parameter names take the form <parameter_sample_redshift>
# if just <parameter> is given, will assume that value is constant for all redshift and
# sample bins (unrealistic)
bias_params:
  b1:
    value: 1.8
    prior:
      min: 0.5
      max: 3.5
  b2:
    value: -0.38878399999999935
    prior:
      min: -1.2
      max: 0.5
  bG2:
    value: -0.22857142857142856
  bGamma3:
    value: 0.43809523809523815
  bphi:
    value: 2.6976
  bphid:
    value: 2.6976
  c0:
    value: 0
  c2:
    value: 0
  c4:
    value: 0
  cfog:
    value: 0
  P_shot:
    value: 0
  a0:
    value: 0
  a2:
    value: 0
