# Fiducial model for the EFT power spectrum
# Based on planck 2018 cosmology

cosmo_params:
  h : 0.6736
  omega_b : 0.02237
  omega_c : 0.1200
  As : 2.100e-9
  ns : 0.9649
  fnl : 0
bias_params:
  b1 : 2.
  b2 : -1.
  bG2 : 0.1
  bGamma3 : -0.1
  bphi : 5
  bphid : 10
  c0 : 5
  c2 : 10
  c4 : -5
  cfog : 5
  P_shot : 10
  a0 : 0
  a2 : 0
