# Fiducial model: planck 2018 baseline 2.5 (base plikHM TTTEEE lowl lowE)
"logA": 3.0447
"ns": 0.96589
"nrun": 0.0
"nrunrun": 0.0
"omch2": 0.12010
"ombh2": 0.022377
"omk": 0.0
"tau": 0.0543
"theta_MC_100": 1.040920
"mnu": 0.06
"w": -1
"wa": 0
"my_foreground_amp": 1.0
"fnl": 0.0
