# File containing fiducial and prior values
# NOTE: This file will be very long if using all redshift and sample bins

# Fiducial model for the EFT power spectrum
# Based on planck 2018 cosmology

varied_cosmo_params: 4
varied_bias_params: 1

cosmo_param_names:
  - h
  - omega_b
  - omega_c
  - As
  - ns 
bias_param_names:
  - b1
  - b2
  - bs2
  - b3nl

cosmo_params:
  h: 
    value: 0.6736
    prior:
      min: 0.4
      max: 1.0
  omega_b: 
    value: 0.02237
    prior:
      min: 0.05
      max: 0.3
  omega_c:
    value: 0.1200
  As:
    value: 2.1e-9
    prior:
      min: 1.2e-9
      max: 2.7e-9
  ns:
    value: 0.9649

# bias parameter names take the form <parameter_sample_redshift>
# if just <parameter> is given, will assume that value is constant for all redshift and
# sample bins (unrealistic)
bias_params:
  b1_0_0:
    value: 1.9
    prior:
      min: 1
      max: 4
  b1_0_1:
    value: 1.0
    prior:
      min: 0.5
      max: 3.0
  b1_1_0:
    value: 1.3
    prior:
      min: 0.6
      max: 3.5
  b1_1_1:
    value: 1.5
    prior:
      min: 0.6
      max: 3.5
  b2:
    value: -1.
  bs2:
    value: -99
  b3nl:
    value: -99
