# file paths are relative w.r.t. the repository directory
# Where to save the network
save_dir: ./emulators/transformer_single_sample_single_redshift/
# Where your training set lives
training_dir: ../../Data/SPHEREx-Data/Training-Set-EFT-1s-1z/
# Location of config file with cosmology + bias parameters
# This file contains all of the parameter default values and ranges
cosmo_dir : ./configs/cosmo_pars/eft_single_sample_single_redshift.yaml

model_type : MLP_single_sample_single_redshift
loss_type : hyperbolic

num_cosmo_params : 4
num_bias_params : 1   # The number of nuisance parameters per tracer+redshift bin
num_samples : 1 
num_zbins   : 1
num_kbins : 25

num_mlp_blocks      : 2
mlp_dims            : [100, 100, 100]
num_block_layers    : 2
use_batchnorm       : False
use_skip_connection : True

num_transformer_blocks : 1
split_dim              : 16

# Training parameters
num_epochs: 300
learning_rate: [1.0e-3]
batch_size: 25
early_stopping_epochs: 25
weight_initialization: He
optimizer_type : Adam
use_gpu : True