
# paths are relative w.r.t. the repository directory
# Where to save the network
save_dir: ./emulators/transformer_1_sample_1_redshift/
# Where your training set lives
training_dir: ../../Data/Training-Set-EFT-1s-1z/
# Location of config file with cosmology + bias parameters
# This file contains all of the parameter ranges
cosmo_dir : ./configs/cosmo_pars/eft_single_sample_single_redshift.yaml

model_type : transformer
loss_type : hyperbolic_chi2

num_cosmo_params : 1
num_bias_params : 2 # The number of nuisance parameters per tracer and redshift bin
num_ells : 5
num_kbins : 50

num_samples : 1
num_zbins   : 1
z_eff: [0.5]

num_mlp_blocks      : 2
mlp_dims            : [250, 250, 250]
num_block_layers    : 3
use_batchnorm       : False
use_skip_connection : True

num_transformer_blocks : 2
split_dim              : 20
split_size             : 20

# Training parameters
num_epochs: 350
learning_rate: [2.0e-04, 5.0e-5]
batch_size: 250
training_set_fraction : 1.0
early_stopping_epochs: 25
weight_initialization: He
optimizer_type : Adam
use_gpu : True
