# Where to save the network
save_dir: /home/joeadamo/Research/SPHEREx/spherex_emu/emulators/transformer_1_sample_1_redshift/
# Where your training set lives
training_dir: /home/joeadamo/Research/Data/SPHEREx-Data/Training-Set-EFT-1t-1z/
# Location of config file with cosmology + bias parameters
# This file contains all of the parameter ranges
cosmo_dir : ./configs/cosmo_pars/eft_single_sample_single_redshift.yaml

model_type : MLP_single_sample_single_redshift
loss_type : mse

num_cosmo_params : 1
num_bias_params : 2 # The number of nuisance parameters per tracer and redshift bin
num_ells : 5
num_kbins : 50

num_samples : 1
num_zbins   : 1
z_eff: [0.5]

num_mlp_blocks      : 2
mlp_dims            : [20, 40, 50]
num_block_layers    : 4
use_batchnorm       : True
use_skip_connection : True

# Training parameters
num_epochs: 350
learning_rate: [4.65e-04, 1.0e-4]
batch_size: 100
training_set_fraction : 1.0
early_stopping_epochs: 25
weight_initialization: He
optimizer_type : Adam
use_gpu : True
