
model:  MLP-single-tracer

input_cosmo_params : 3
input_nuisance_params : 1 # The number of nuisance parameters per tracer
output_kbins : 20

num_tracers: 1
z_eff: [0.1]

num_mlp_blocks      : 1
num_block_layers    : 3
use_batchnorm       : True
use_skip_connection : True
mlp_dims            : [5, 20]

# Training parameters
num_epochs: 300
learning_rate: [1e-3]
batch_size: 100
early_stopping_epochs: -1
weight_initialization: He

# Where to save the network
save_dir: /Home/Joeadamo/Research/SPHEREx/spherex_emu_emulators/mlp_single_tracer/
# Where your training set lives
training_dir: /Home/Joeadamo/Research/SPHEREx/training_set_single_tracer/